title: Adam Finlayson
tagline: Lead AWS/JavaScript Cloud Developer in Evanston/Chicago
summary: |
  AWS cloud and JavaScript developer.
  Once mapped the maze of twisty little passages all alike.
  A petal from a steel magnolia.

  Verbs: connect, empower, build
