title: Adam Finlayson
tagline: Lead AWS/JavaScript Cloud Developer in Evanston/Chicago
summary: |
  A petal from a steel magnolia.
  AWS cloud and JavaScript developer based in Evanston, IL.
  Once mapped the maze of twisty little passages all alike.

  Verbs: connect, empower, build
